# Generated by Django 5.0.6 on 2025-07-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('home', 'Home Delivery'), ('pickup', 'Pickup from Store')], default='home', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Online Payment (Razorpay)'), ('cod', 'Cash on Delivery')], default='razorpay', max_length=20),
        ),
    ]
