# Generated by Django 5.0.6 on 2025-07-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_cancelled_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('N', 'None'), ('P', 'Pending'), ('S', 'Successful'), ('F', 'Failed')], default='N', max_length=1),
        ),
    ]
