# Generated by Django 5.0.6 on 2025-06-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='price',
        ),
    ]
