# Generated by Django 5.0.6 on 2025-06-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_treatment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='achievement_images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='disease_images'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='treatment_images'),
        ),
    ]
