# Generated by Django 5.0.6 on 2025-07-08 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_achievement_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='clinic.disease'),
        ),
    ]
